### ISSUE TITLE
license Info

### ISSUE THREAD

**Issue by LalitPradhan** [abiusx/CLPatchMatch#2]
Please let me know the license information for using this code.

**Comment by abiusx** [comment]
I believe this was released as LGPL. You are free to use it commercially.
-A

**Comment by LalitPradhan** [comment]
Thanks for the update. Closing this,

**Comment by abiusx** [comment]
Lalit,
I need to ask you a question but couldn't find your email on your profile. Please email me git@abiusx.com thanks!

**Comment by LalitPradhan** [comment]
Hi,
I just saw this now. Apologies for missing out on this. Do you want me to mail you?
