### ISSUE TITLE
What is the Licence? 

### ISSUE THREAD

**Issue by ylockerman** [abiusx/CLPatchMatch#3]
Hi,

I am considering using this code and was wondering what license it is under?

Thank You,
YL

**Comment by ylockerman** [comment]
Just saw the closed comment. Closing comment.

**Comment by abiusx** [comment]
Hello,
The code is licensed as LGPL!
Regards
-Abbas

**Comment by abiusx** [comment]
YL,
I need to ask you a question but couldn't find your email on your profile. Please email me git@abiusx.com thanks!
